version: '3.7'
services:
  server:
    image: trump_earth_defense-server
    restart: always
    ports:
      - '9000:9000'
    build: 
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/server
      - /server/node_modules
    depends_on:
      - mongo
    networks: 
      - trumpEarthDefense-network
  client:
    image: trump_earth_defense-client
    restart: always
    ports:
      - '3000:3000'
    build: 
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/client 
      - /client/node_modules
    links:
      - server
    networks: 
      - trumpEarthDefense-network
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - '27017:27017'
    networks: 
      - trumpEarthDefense-network
networks:
  trumpEarthDefense-network:
    driver: bridge