version: '3'
services:
  app:
    container_name: billboard
    restart: always
    build: .
    volumes:
      - .:/billboard
      - /billboard/node_modules
      - /billboard/client/node_modules
    ports:
      - '80:3000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'